version: "2"
services:
    db:
        image: prom/prometheus
        volumes:
            - ./etc/:/etc/prometheus/
            - prometheus_data:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-storage.local.path=/prometheus'
        expose:
            - 9090
        ports:
            - "9090:9090"
        network_mode: host
    grafana:
        image: grafana/grafana
        depends_on:
            - db
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        env_file:
            - config.grafana
volumes:
    prometheus_data: {}
    grafana_data: {}
