export SEBAK_SECRET_SEED=SBECGI3FSCYHNQIMANNCWQSVA6S5C6L4BXFKAPMBAMI5V47NWXNE37MN
export SEBAK_PUBLIC_KEY=GDPWP7BOOMEKK6DUQELQD7H5NEENPLDTQQWYOIBSFS65WH7DNG7UWVKB
sebak wallet payment $SEBAK_PUBLIC_KEY 1000000 $SEBAK_SECRET_SEED --endpoint=http://localhost:2821 --network-id=sebak-test-network --create --verbose
