global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: sebak_node
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:2821','localhost:2822','localhost:2823','localhost:2824']


